### PR TITLE
Feature/Setup jest

### LINKED ISSUE #2: Setup jest in the project
https://jestjs.io/docs/getting-started

### PR DESCRIPTION
**Pull request by Willian1661**
@eerison 
i added the node modules and dependencies to run the jest.
in this branch are the same files that are in master, but in jest-test have the test files

Close: #2

### CODE REVIEW

**Comment by eerison** [comment]
@Willian1661 add your node_modules folder into the gitignore

**Comment by eerison** [comment]
@Willian1661 let your PR as DRAFT , and when it's able to review again, you remove the draft  ;)

**Comment by eerison** [comment]
Create a better title for your PR like

Feature/Setup jest 

And refer the issue into the description

**Comment by Willian1661** [comment]
ok
hey i'am thinking about deleting the module files here in the remote to do a pull on my local
because my terminal it's aborting the process while i pull the files.

**Comment by Willian1661** [comment]
because my branches have diverged, so a can't either do a merge or a pull 😅
so i was thinking about i delete this remote branch that i made and do all over again.
what you think ? or i have other way?

**Comment by eerison** [comment]
> because my branches have diverged, so a can't either do a merge or a pull sweat_smile so i was thinking about i delete this remote branch that i made and do all over again. what you think ? or i have other way?

when you have time, let me know we can make a call and I explain you :)

**Comment by Willian1661** [comment]
i can from now and so on

**Pull request merged**
